### ISSUE TITLE
Problem with generated URL

### ISSUE THREAD

**Issue by realeast** [rmorse/search-filter#2]
I have my posts page set to "/journal" on www.mysite.com/wp-admin/options-reading.php.

When I run the Search & Filter plugin, the URLs generated look like this, e.g.

www.mysite.com/category/test_category?s=test_term

But what the plugin needs to generate in my case is:

www.mysite.com/journal/category/test_category?s=test_term

Is there a setting I'm missing? Or is there some way to fix this?

Please help if possible. I'd really like to get your brilliant plugin working! Thank you.

**Comment by rmorse** [comment]
Hey realeaset... you seem to have a non standard WP setup.  Categories are always shown like this in WP:

www.mysite.com/category/test_category?s=test_term

If you wanted to change the slug for category you can do so by heading to permalinks in your WP admin, and changing "Category Base"

I'm assuming if you go to this URL 

www.mysite.com/category/test_category

Then you will see all listings for the test category, displayed using your category template?

**Comment by realeast** [comment]
Hi,

As I mentioned, my site has a posts page set: my posts do NOT appear under the root (www.mysite.com) but instead at the page I've set: www.mysite.com/journal. 

This is a common strategy when you have a static front page for example.

So I need the Search & Filter plugin to generate URLs based on the real location of my posts, not the assumed location under the root.

**Comment by rmorse** [comment]
Hi realest I get that.. but for example, if you were to view the category page for one of your categories, what would your URL be? Ie, what URL would load your category template?

Just to let you know how this plugin works... it doesn't actually modify the WordPress search in most cases, it basically rewrites the URL to something WordPress already knows how to handle.

So a normal way of browsing categories on any theme (without this plugin) would be under a URL like this:

www.mysite.com/category/test_category

regardless if you change your default posts page.

Then the category template would automatically kick in.

I hope this makes sense

**Comment by realeast** [comment]
Hi,

I think perhaps my theme is a bit 'non-standard' :-) Maybe that explains the lack of compatibility for me.

Anyway, I've managed to hardwire a more sophisticated search now, so everything's fine.

Thanks anyway.
