### ISSUE TITLE
date and daterange showing up?

### ISSUE THREAD

**Issue by Bradsap** [rmorse/search-filter#5]
![capture-nodate-range](https://f.cloud.github.com/assets/4694724/2431622/6f638db0-ad39-11e3-8b60-951ef29886ba.JPG)

 Assuming that the date and date range are a select list, I'm having some trouble getting the date range field to show up. Currently it just appears to be a simple text input and type="date" but no default value/choices. 

Just using your example shortcodes to test:
[searchandfilter fields="search,post_date" types=",date" headings=",Post Date"]

[searchandfilter fields="search,post_date" types=",daterange" headings=",Post Date"]

[searchandfilter fields="search,post_date,category,post_tag,post_format,taxonomyone,taxonomytwo" types=",daterange,select,select,select,select,select" hierarchical=",1" headings=",Post Date,Categories,Tags,Post Format,Taxonomy One,Taxonomy Two" submit_label="Search Events"]

**Comment by rmorse** [comment]
Hey @Bradsap, if you check the documentation it says the only implementation of this is using the HTML5 date input type. If your browser does not support it, it will revert to a plain text input.  If you look on a modern browser, or one that has support for this you will see a nice date picker (like chrome).

With this version of the plugin, I didn't want it to start getting messy with front end code (such as CSS & JS) so I've left it as plain as possible.  I did plan on writing an article on how to implement this but haven't had the time.

I would take a look at tutorials for the HTML date field and graceful degradation using the jQuery date picker - a quick google pulled this up - http://weblog.west-wind.com/posts/2012/Nov/08/HTML5-Input-typedate-Formatting-Issues

I am working on a pro version of the plugin which will have support for this out the box as well as some nice UI elements such as range sliders and meta data etc - if you're interested leave your email over here http://www.designsandcode.com/contact-us-2/
