### ISSUE TITLE
Enable plugin translation via translate.wordpress.org

### ISSUE THREAD

**Issue by tobifjellner** [rmorse/search-filter#62]
Some small fixes are needed in order to enable translation of this plugin at translate.wordpress.org:

Reference: https://wp-info.org/tools/checkplugini18n.php?slug=search-filter

1. Your text-domain must be equal to the plugin slug. In the declaration and in every call to the translation functions, you need to use: "search-filter" instead of "searchfilter".

2. I didn't search your code to check if you're calling load_plugin_textdomain() correctly. But if you set "Requires at least" in Readme to 4.6 or later (which by now should be a rather safe thing to do), then you don't need that command.

**Comment by tobifjellner** [comment]
Closing this one. I can see that you've ignored a PR from Ramiy 3.5 years ago, and that strings in the plugin still even don't call the translation functions.

**Comment by rmorse** [comment]
Hey @tobifjellner , I'm about 3 weeks away from dropping a complete rewrite - this version of the plugin has been neglegted for far too long - and strings will be properly translatable :)

**Comment by tobifjellner** [comment]
Thanks. I'll bring the good news to a Swedish user that was trying to translate your plugin to Swedish :)
