### ISSUE TITLE
PHP Deprecated: Required parameter $output follows optional parameter $depth in /plugins/search-filter/of-taxonomy-walker.php on line 17

### ISSUE THREAD

**Issue by pgnicolau** [rmorse/search-filter#72]
Hey Team - I'm using the Search and Filter plugin for a client and we are in the middle of upgrading to php 8. 

We're receiving the following deprecation errors:

**Deprecated: Required parameter $args follows optional parameter $depth in /wp-content/plugins/search-filter/of-taxonomy-walker.php on line *17***

**Deprecated: Required parameter $output follows optional parameter $depth in /wp-content/plugins/search-filter/of-taxonomy-walker.php on line *17***

Let me know what the plans are for php 8 compatibility and resolving such issues.

THANKS!!
Gabs

**Comment by rmorse** [comment]
Thanks for this! It was fixed in the latest update released last week.
