### ISSUE TITLE
advice on adapting to do a live filter

### ISSUE THREAD

**Issue by davidmaxwaterman** [rmorse/search-filter#9]
Hi,

I have some experience of html/css/js but am newish to php and completely new to wordpress.

I've been tasked by some people to change the way the search form looks and I think I've done that, though perhaps in a completely hacky way (ie I've just changed the plugin code itself so it'll be overwritten when/if it is updated - though I have a copy).

Anyway, I have also been asked to implement a 'live search/filter'. I already have event handlers on the multiple select checkboxes I'm using, so I can initiate a filter at that point, but I'm wondering how I can query wordpress (it's a database, right?) to get the search/filter results in json so I can then show/hide appropriately.

Any advice on doing this?

Thanks,

Max.

**Comment by rmorse** [comment]
Hey Max, do you mean like in the pro version? http://demo.designsandcode.com/sfpro-movie-reviews/
;)

**Comment by davidmaxwaterman** [comment]
Hi, yes, I spotted that sometime after I posted this question - I just assumed no one was paying attention to github issues, else I would have closed this.

Thanks anyway...I'll close this now since I'm unlikely to get any help.

**Comment by rmorse** [comment]
No worries, unfortunately its a bit complicated to get it working with Ajax and would at least require something like a tutorial to explain properly anyway!
